### ISSUE TITLE
Spam fra dette repoet

### ISSUE THREAD

**Issue by ThomasKasene** [navikt/kafka-embedded-env#48]
I skrivende stund er det ~850 medlemmer i `navikt/nav-developers` teamet, og slett ikke alle er interessert i å få e-poster hver gang Dependabot finner på noe her.

Kan jeg foreslå å heller gi `navikt/nav-developers` Triage-rollen og fjerne hele `CODEOWNERS`-fila i så vi forhåpentligvis slipper å bli nedspammet av dette repoet? Da vil vi fortsatt ha de samme rettighetene men ikke bli påtvunget e-postspammen som kommer med å være code owner (er hypotesen hvertfall).

**Comment by tronghn** [comment]
Fjernet codeowners. Write-rollen består.
