### ISSUE TITLE
extend zookeeper command whitelist

### ISSUE THREAD

**Issue by thrau** [navikt/kafka-embedded-env#59]
i would like to be able to run `dump` and `stat` on zookeeper, but it seems that kakfa-embedded-env is pretty strict in the allow list:

https://github.com/navikt/kafka-embedded-env/blob/2f3b2c4dd1978951dcb84fbd94b5b1e0adbdbb26/src/main/kotlin/no/nav/common/embeddedzookeeper/ZKServer.kt#L36

i couldn't find a way to reliably overwrite these properties. is there a particular reason why the whitelist isn't just `"*"`? would you be willing to accept a PR that changes that?

btw thanks for this fantastic library!

**Comment by oysbak** [comment]
Stenger denne siden den er gammel
