### ISSUE TITLE
Error dersom man har confluent versjon 5.1.2

### ISSUE THREAD

**Issue by MikAoJk** [navikt/kafka-embedded-env#8]

**Comment by MikAoJk** [comment]
4:12:45 [main ] ERROR k.log.LogManager     : 
Shutdown broker because none of the specified log dirs from /var/folders/n1/m9y0n2r95z98p84rpmqzq93h0000gp/T/
inmemorykafkabroker/e809b32b-fc9b-4a9b-aeaf-67c9dd7df35d/logs can be created or validated

**Comment by TheUnnamedDude** [comment]
Nå er jeg usikker på hvilke confluent versjon vi kjører i produksjon, men tanken er at embedded env skal matche den versjonen. Det er en del ting som kan føre til dette problemet:
* Siden det ikke er noen API for embeddingen gjort i kafka-embedded-env benytter den interne apier som ikke er stabile og kan endre seg.
* embedded-env kan forvente en viss oppførsel som ikke er spesifikk for apiet.
* Når man bumper confluent versjonen kan man også ende opp med en missmatch på bibliotek versjoner som fører til at embedded-env ikke fungerer.

Uansett er det nok en god idé å kun bumpe patch versjonen og beholde major og minor samme som i produksjon. Da unngår man problemer med kompatibelt og forsikrer seg om at man ikke tar i bruk funksjonalitet som ikke er i produksjon.
