### ISSUE TITLE
Embedded kafka får konflikt med seg selv i spek-tester

### ISSUE THREAD

**Issue by tiafiring** [navikt/kafka-embedded-env#9]
Jeg bruker embedded kafka versjon 2.1.1 i spek-tester og får denne feilen ved kjøring: 
java.nio.file.FileSystemException: C:\Users\F133008\AppData\Local\Temp\inmemorykafkabroker\b39bc107-6ca0-4157-9b1a-9c1cd59c6cf2\logs\__consumer_offsets-0\00000000000000000000.timeindex: The process cannot access the file because it is being used by another process.

Dette skjer både fra intellij og fra kommandolinjen, og hos meg skjer det konsekvent. 

Her er testen som jeg opplever denne feilen i: https://github.com/navikt/syfosmvarsel/blob/master/src/test/kotlin/no/nav/syfo/syfosmvarsel/avvistsykmelding/AvvistSykmeldingServiceKtTest.kt

**Comment by tronghn** [comment]
Versjon 2.1.1 endrer på håndtering av paths som sikkert ikke fungerer så godt på Windows. Midlertidig løsning er å nedgradere til 2.1.0 (pathhåndteringen er egentlig det eneste som er forskjellen mellom de to versjonene).

**Comment by tronghn** [comment]
Fikset i #10.
